### ISSUE TITLE
issue to track the patch mremap-underflow.diff

### ISSUE THREAD

**Issue by andrewrk** [ziglang/qemu-static#4]
Just so we don't forget to pay attention to upstream bug report https://bugs.launchpad.net/qemu/+bug/1876373 and periodically remind the qemu devs to look at the patch we sent upstream.

related: https://github.com/ziglang/zig/issues/5245

upstream patch: https://lists.gnu.org/archive/html/qemu-trivial/2020-05/msg00000.html

Once this repo updates to a newer QEMU release which contains the fix, the patch can be removed from this repo, and this issue can be closed.

**Comment by marler8997** [comment]
here's the correct patch: https://lists.gnu.org/archive/html/qemu-devel/2020-05/msg00183.html

the original one was incorrect

**Comment by marler8997** [comment]
Patch appears to have been accepted by "Laurent" (https://lists.gnu.org/archive/html/qemu-devel/2020-05/msg07875.html)

Not sure if that means it will show up on the community's master branch...these old-timey repos are so confusing to contribute to.
